### ISSUE TITLE
"ajax error"

### ISSUE THREAD

**Issue by GJRobert** [i3thuan5/lomaji-tsuanuann#15]
Kiù lâng--oo! Tsuè-kūn huat-hiān tsuán-uānn-khì ká-ná phái--khì.

**Comment by sih4sing5hong5** [comment]
感謝報阮知， https://github.com/i3thuan5/lomaji-tsuanuann/commit/07c0376600dfdde962a3d6ab14a64f4594b1a0a2 修好--ah
